import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Inventory</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main>
				<div className="backpack">
					<img
						src="/inventory.png"
						className="inventoryImage"
					></img>
					<div className="inventoryGrid">
						<img
							className="item"
							src="/pumpkin.png"
						></img>
						<img
							className="item"
							src="/cabbage.png"
						></img>
						<img
							className="item"
							src="/carrot.png"
						></img>
					</div>
				</div>
			</main>
		</>
	);
}
