import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const items = [
		{
			name: "Cabbage",
			src: "/cabbage.png",
		},
		{
			name: "Carrot",
			src: "/carrot.png",
		},
		{
			name: "Pumpkin",
			src: "/pumpkin.png",
		},
	];
	useEffect(() => {
		console.log("Version 0.0.3 loaded");
		for (let i = items.length; i < 5 * 7; i++) {
			items.push({ name: "", src: "blank.png" });
		}
	}, []);

	return (
		<>
			<Head>
				<title>Inventory</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main>
				<div className="backpack">
					<img
						src="/inventory.png"
						className="inventoryImage"
					></img>
					<div className="inventoryGrid">
						{items.map((item, index) => {
							console.log(item.name);
							return (
								<img
									key={index}
									className="item"
									src={item.src}
								></img>
							);
						})}
					</div>
				</div>
			</main>
		</>
	);
}
{
	/* <img
							className="item"
							src="/pumpkin.png"
						></img>
						<img
							className="item"
							src="/cabbage.png"
						></img>
						<img
							className="item"
							src="/carrot.png"
						></img> */
}
